on:
  push:
    branches: master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version-file: package.json
          cache: npm
      - run: npm ci
      - run: npm run lint

  format:
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version-file: package.json
          cache: npm
      - run: npm ci
      - run: npm run format:check

  build:
    runs-on: ubuntu-26.04
    needs: [lint, format]
    outputs:
      package_path: ${{ steps.version.outputs.package }}
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version-file: package.json
          cache: npm
      - run: npm ci
      - id: version
        name: Set PR package version
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
        run: node tools/calculate-package-version.mjs
      - run: npm run build
      - run: npm pack
      - uses: actions/upload-artifact@v7
        with:
          path: ${{ steps.version.outputs.package_path }}
          archive: false
          if-no-files-found: error

  publish:
    needs: build
    runs-on: ubuntu-26.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/setup-node@v7
        with:
          node-version-file: package.json
          registry-url: https://npm.pkg.github.com
          scope: '@2chevskii'
      - uses: actions/download-artifact@v8
        with:
          name: ${{ needs.build.outputs.package_path }}
      - env:
          NODE_AUTH_TOKEN: ${{ github.token }}
          PACKAGE: ./artifacts/${{ needs.build.outputs.package_path }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: npm publish "$PACKAGE" --registry https://npm.pkg.github.com --tag "pr-${PR_NUMBER}" --ignore-scripts

  build_docs:
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version-file: package.json
          cache: npm
      - run: npm ci
      - run: npm run docs:build
      - uses: actions/upload-pages-artifact@v5
        with:
          path: docs/.vitepress/dist/
          include-hidden-files: true
